# Generated by Django 5.0.6 on 2026-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
