# Generated by Django 5.0.6 on 2026-03-04 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0004_alter_tipoactivo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(help_text='Nombre del técnico o empresa responsable', max_length=200)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion_problema', models.TextField(blank=True, null=True)),
                ('acciones_realizadas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='activos.activo')),
            ],
        ),
    ]
