# Generated by Django 5.0.6 on 2026-03-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='mantenimientos/comprobantes/'),
        ),
    ]
