# Generated by Django 5.0.6 on 2026-04-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_backuphistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistorial',
            name='descargado',
            field=models.BooleanField(default=False),
        ),
    ]
