# Generated by Django 5.0.6 on 2026-04-02 20:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_backuphistorial_descargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuphistorial',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Santiago\\Desktop\\ProyectoSCI\\Backend\\api_sci\\private_media'), upload_to='backups/'),
        ),
    ]
