# Generated by Django 5.0.6 on 2026-03-23 19:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0003_caracteristica_tamano'),
        ('areas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('responsable', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sistema', models.CharField(blank=True, max_length=20)),
                ('estado_real', models.CharField(blank=True, max_length=20, null=True)),
                ('encontrado', models.BooleanField(default=True)),
                ('resultado', models.CharField(blank=True, choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='activos.activo')),
                ('area_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='areas.area')),
                ('area_sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='areas.area')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='auditoria.auditoria')),
            ],
            options={
                'unique_together': {('auditoria', 'activo')},
            },
        ),
    ]
