# Generated by Django 5.0.6 on 2026-03-23 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_initial'),
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='areas.area'),
        ),
    ]
