# Generated by Django 5.0.6 on 2026-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_auditoria_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='tipo',
            field=models.CharField(blank=True, choices=[('mantenimiento', 'Mantenimiento'), ('prestamo', 'Préstamo')], max_length=20, null=True),
        ),
    ]
