# Generated by Django 5.0.6 on 2026-03-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_auditoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='tipo',
            field=models.CharField(blank=True, choices=[('mantenimiento', 'Mantenimiento'), ('prestamo', 'Préstamo'), ('disponible', 'Disponible')], max_length=20, null=True),
        ),
    ]
