# Generated by Django 5.0.6 on 2026-03-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='activos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('mantenimiento', 'En mantenimiento'), ('baja', 'Baja')], default='disponible', max_length=20)),
                ('frecuencia_mantenimiento', models.IntegerField(default=60, help_text='Cada cuantos días se debe hacer mantenimiento preventivo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_dato', models.CharField(choices=[('text', 'Texto'), ('int', 'Número entero'), ('float', 'Número decimal'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('select', 'Selección'), ('multiselect', 'Selección múltiple')], default='text', max_length=20)),
                ('obligatorio', models.BooleanField(default=False, help_text='Indica si esta característica es obligatoria')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValorCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
