# Generated by Django 5.0.6 on 2026-03-11 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='areas.area'),
        ),
        migrations.AddField(
            model_name='opcioncaracteristica',
            name='caracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='activos.caracteristica'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='tipo_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='activos.tipoactivo'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tipo_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.tipoactivo'),
        ),
        migrations.AddField(
            model_name='valorcaracteristica',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='activos.activo'),
        ),
        migrations.AddField(
            model_name='valorcaracteristica',
            name='caracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.caracteristica'),
        ),
        migrations.AddField(
            model_name='valorcaracteristica',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.opcioncaracteristica'),
        ),
        migrations.AlterUniqueTogether(
            name='caracteristica',
            unique_together={('tipo_activo', 'nombre')},
        ),
    ]
