# Generated by Django 5.0.6 on 2026-02-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='responsable_directo',
        ),
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('mantenimiento', 'En mantenimiento'), ('baja', 'Baja')], default='disponible', max_length=20),
        ),
    ]
