# Generated by Django 5.0.6 on 2026-03-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='tamano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
