# Generated by Django 5.0.6 on 2026-02-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_remove_activo_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactivo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
