# Generated by Django 5.0.6 on 2026-03-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_tipoactivo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactivo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
