# Generated by Django 5.0.6 on 2026-03-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_alter_tipoactivo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='frecuencia_mantenimiento',
            field=models.IntegerField(default=60, help_text='Cada cuantos días se debe hacer mantenimiento preventivo'),
        ),
    ]
